/*
 * TPM2CH0.c
 *
 *  Created on: Oct 29, 2020
 *      Author: jprr2
 */

#include "derivative.h" /* include peripheral declarations */
#include "System.h"
#include "PIT.h"

unsigned short t = 0;
int distancia = 0;
unsigned char rising = 1;

void TPM2_init(){
	SIM_SOPT2 |= (3<<24);                           //TPM clock MCGIRCLK 4MHz	
	SIM_SCGC6 |= (1<<26);                           //clk TPM2
	
	TPM2_SC |= (1<<3) + (1<<6);                     //clk source 4MHz & timer overflow intr enable
	TPM2_C0SC |= (1<<6);                            //channel intr enable
	TPM2_C0SC |= (3<<2);                            //input capture on both rising and falling edge
	TPM2_CONF |= (3<<6);                            //TPTMR runs in debug mode
	NVIC_ISER |= (1<<19);                           //intr enable TPM2
}

void FTM2_IRQHandler(){
	int time;
	if (TPM2_SC & (1<<7)){                          //intr generated by overflow
		TPM2_SC |= (1<<7);                          //erasing flag w1c
		pulso_sensor_us();
	}
	else if (TPM2_C0SC |= (1<<7)){                   //intr generated by channel event
		TPM2_C0SC |= (1<<7);                         //erasing flag w1c
		
		if (rising){
			TPM2_CNT = 0;
			rising = 0;
		}else{
			t = TPM2_C0V;
			time = ((t)*250)/1000;                   //tiempo en us
			distancia = time/58;					 //distancia en cm
			rising = 1;
			pulso_sensor_us();
		}
	}
}
